Coconut Oil (365): 1
Extra Virgin Olive Oil (365): 0
Fish Oil (Carlson): 1

Eggs (org) (Vital): 3

Arugula (365): 30
Kale (org) (365): 60

Carrots (365): 28
Mushrooms (white) (365): 100
Radish (365): 28
Salsa (Casa Chicas): 3
Serrano Pepper (365): 2

Avocado (haas) (365): 1

Parmesan Cheese (365): 7
Mozzarella Cheese (365): 7
Feta Cheese (365): 7
Blue Cheese (365): 7

Pecans (365): 7
Walnuts (365): 7

Chia Seeds (365): .0
Pumpkin Seeds (365): 14
