Broccoli (365): 40

Coconut Oil (365): 1
Extra Virgin Olive Oil (365): 1
Fish Oil (Carlson): 1

Eggs (org) (Vital): 2

Arugula (365): 30
Kale (org) (365): 60

Carrots (365): 30
Mushrooms (white) (365): 90
Radish (365): 30
Salsa (Casa Chicas): 3
Serrano Pepper (365): 2

Avocado (haas) (365): 1

Parmesan Cheese (365):
Mozzarella Cheese (365):
Feta Cheese (365):
Blue Cheese (365):

Pecans (365):
Walnuts (365):

Chia Seeds (365):
Pumpkin Seeds (365):
